### ISSUE TITLE
Cannot find class "RefreshController", incompatible with latest version of flutter. 

### ISSUE THREAD

**Issue by annol389** [peng8350/flutter_pulltorefresh#441]
Hi! I have the following problem:

I have imported pull_to_refresh v 1.6.4:

```
version: 1.0.3+0

environment:
  sdk: ">=2.2.2 <3.0.0"
  #flutter: "^0.1.2"

dependencies:
  flutter:
    sdk: flutter
  pull_to_refresh: ^1.6.4
```

Ran `flutter pub get`. 

And have added it to my dart file:
```
import 'package:pull_to_refresh/pull_to_refresh.dart';
```

In my dart file, I am able to use some of the packaged classes, like the `RefreshIndicator` class and the `ClassicFooter` class, but I am unable to use the `RefreshController` class. 

I have already found the solution. The latest version of `pull_to_refresh` is not compatible with the latest version of flutter. So using

```
pull_to_refresh: 1.6.3
```

solves the issue. However, it should be noted that the latest version of `pull_to_refresh` breaks on the latest version of flutter. 

I am posting this to help anyone that may have the same problem, and ensure that the author of lib knows about the issue.
